In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("Demo.xlsx")
df.head()

,Roll no,Name of Student,Previous Year SPPU Total Marks out of 1400,%,UT 1 Marks,%.1,50% maks of Previous Year SPPU Result,50% Marks of Unit Test 1,Total 100%,Gender
0,1,RAVAL MEET MAHESH,1131,NaN,29.0,96.666667,44.0,41,85.0,M
1,2,HUMBE BHAKTI RAJENDRA,1107,79.071429,29.0,96.666667,42.0,41,83.0,F
2,3,MARATHE SANSKRUTI JAGDISH,995,71.071429,27.0,90.000000,41.0,41,82.0,F
3,4,THAKARE MRUNALI VINOD,1077,76.928571,28.0,93.333333,43.0,39,82.0,F
4,5,BHONGALE OMKAR MADHUKAR,1064,76.000000,28.0,93.333333,42.0,38,80.0,M

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 10 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Roll no                                      74 non-null     int64
 1   Name of Student                              74 non-null     str
 2   Previous Year SPPU Total Marks out of  1400  74 non-null     int64
 3   %                                            72 non-null     float64
 4   UT 1 Marks                                   72 non-null     float64
 5   %.1                                          71 non-null     float64
 6   50% maks of Previous Year SPPU Result        73 non-null     float64
 7   50% Marks of Unit Test 1                     74 non-null     int64
 8   Total 100%                                   74 non-null     float64
 9   Gender                                       74 non-null     str
dtypes: float64(5), int64(3), str(2)
memory usage: 5.9 KB

In [4]:
df.describe()

,Roll no,Previous Year SPPU Total Marks out of 1400,%,UT 1 Marks,%.1,50% maks of Previous Year SPPU Result,50% Marks of Unit Test 1,Total 100%
count,74.000000,74.000000,72.000000,72.000000,71.000000,73.000000,74.000000,74.000000
mean,37.500000,951.567568,68.197421,23.541667,78.779343,33.984344,33.635135,67.160232
std,21.505813,141.310024,9.504182,4.924608,16.322537,6.579955,4.961701,9.791757
min,1.000000,542.000000,43.428571,4.000000,13.333333,0.000000,21.000000,31.000000
25%,19.250000,880.000000,63.142857,21.000000,70.000000,31.357143,31.000000,62.928571
50%,37.500000,970.000000,69.285714,24.000000,80.000000,34.607143,34.000000,68.375000
75%,55.750000,1059.750000,75.660714,27.250000,91.666667,37.821429,37.000000,72.919643
max,74.000000,1203.000000,85.928571,29.000000,96.666667,44.000000,41.000000,85.000000

In [5]:
df.dtypes

Roll no                                          int64
Name of Student                                    str
Previous Year SPPU Total Marks out of  1400      int64
%                                              float64
UT 1 Marks                                     float64
%.1                                            float64
50% maks of Previous Year SPPU Result          float64
50% Marks of Unit Test 1                         int64
Total 100%                                     float64
Gender                                             str
dtype: object

In [9]:
df = pd.read_csv("IRIS.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [10]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [11]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [12]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object